-- PATHS GENERALES (Configurar para cada usuario)
--------------------------------------------------------------------------------------------------------------------
data_dir = "C:\\Users\\Cristian\\Documents\\Cristian\\ItLightens\\bin\\data\\"
max_dir = "C:\\Users\\Cristian\\Documents\\Cristian\\ItLightens\\max\\"
--------------------------------------------------------------------------------------------------------------------

filein ( (getDir #scripts) + "\\"+"project_config.ms")