-- PATHS GENERALES (Configurar para cada usuario)
--------------------------------------------------------------------------------------------------------------------
data_dir = "C:\\Users\\Cristian\\Documents\\Cristian\\ItLightens\\bin\\data\\"
objMax_dir = "C:\\Users\\Cristian\\Documents\\Cristian\\ItLightens\\max\\maxObjects\\"
--------------------------------------------------------------------------------------------------------------------

filein ( (getDir #scripts) + "\\"+"project_config.ms")