-- PATHS RELATIVOS a los anteriores (por lo general no tocar)
--------------------------------------------------------------------------------------------------------------------
--Data
meshes_dir = data_dir + "meshes\\"
staticMeshes_dir = data_dir + "static_meshes\\"
scenes_dir = data_dir + "scenes\\"
materials_dir = data_dir + "materials\\"
objMax_dir = max_dir + "maxObjects\\"
helperMax_dir = max_dir + "maxHelpers\\"
--Scripts
scriptsDir = (getDir #scripts) + "\\"
mcvScriptsDir = scriptsDir + "mcv\\"
mcvResources = mcvScriptsDir + "\\resources\\"
mcvTools = mcvScriptsDir + "\\tools\\"
mcvParsingDir = mcvScriptsDir + "\\parsing\\"
mcvMacrosDir = mcvScriptsDir + "\\macros\\"
--------------------------------------------------------------------------------------------------------------------

-- EXTENSIONES
--------------------------------------------------------------------------------------------------------------------
mesh_ext = ".mesh"
staticMesh_ext = ".static_mesh"
skel_ext = ".skeleton"
--------------------------------------------------------------------------------------------------------------------