-- PATHS GENERALES (Configurar para cada usuario)
--------------------------------------------------------------------------------------------------------------------
data_dir = "F:\\master\\Repo\\ItLightens\\bin\\data\\"
max_dir = "F:\\master\\Repo\\ItLightens\\max\\"
--------------------------------------------------------------------------------------------------------------------
filein ( max_dir + "scripts\\project_config.ms")